local_clutter_cairomm_libs = $(top_builddir)/clutter-box2d/clutter-box2dmm/libclutter-box2dmm-$(API_VER).la

LIBS  = $(CLUTTER_CAIROMM_LIBS) $(local_clutter_cairomm_libs)

all_includes = -I$(top_builddir)/clutter-box2d -I$(top_srcdir)/clutter-box2d \
              $(CLUTTER_CAIROMM_CFLAGS)

DEFS = @DEFS@
DEFAULT_INCLUDES =
INCLUDES = -I. -I$(srcdir) $(strip $(all_includes))

